# Generated by Django 2.2.5 on 2020-10-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20201013_2359'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rule',
            new_name='HouseRule',
        ),
        migrations.AddField(
            model_name='room',
            name='facilities',
            field=models.ManyToManyField(to='rooms.Facility'),
        ),
        migrations.AddField(
            model_name='room',
            name='house_rules',
            field=models.ManyToManyField(to='rooms.HouseRule'),
        ),
    ]
