# Generated by Django 2.2.5 on 2020-10-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20201017_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateField(),
        ),
    ]
